export const data = [
  "https://oregonriverrentals.com/rentals/inflatable-paddle-board/",
  "https://cghooks.com/boat-watersport-rentals/stand-up-paddle-board-rentals/",
  "https://sandiegosuprentals.com/",
  "https://lazydog.com/paddleboard/",
  "https://www.acadiasup.com/",
  "https://juneaukayak.com/juneau-kayak-rentals/paddle-boards/",
  "https://www.prosupshop.com/",
  "https://www.5280paddlesports.com/rentals.html",
  "https://pwhawaii.org/paddle-activities/paddleboards/",
  "https://austinrowing.org/paddle/",
  "https://ctriverquest.com/portfolio/osprey_eagle/",
  "https://ameliarivercruises.com/product/t-shirt-osprey/",
  "https://discovercayugalake.org/public-boat-cruises-cayuga-lake-finger-lakes-ithaca-ny/",
  "https://floridawatertour.com/about-our-vessel/",
  "https://www.sweeneyscruiseco.com/our-fleet/osprey/",
  "https://experiencefingerlakes.com/discover-cayuga-lake-boat-tours/",
  "https://www.capewatertaxi.com/narrated-tours/osprey-banding-tour/",
  "https://www.lasolaspaddleboards.com/",
  "https://chesapeakepaddlesports.com/",
  "https://www.ohanasurfproject.com/stand-up-paddle-board-rentals-waikiki/",
  "https://paddlesoutdoorrentals.com/rentals/paddle-board-rentals/",
  "https://paddleboardnewportbeach.com/",
  "https://www.kailuabeachadventures.com/kailua-paddle-board-rentals",
  "https://rockymtnpaddleboard.com/denver/",
  "https://www.tourglacier.com/whitefish-lake-state-park-rentals",
  "https://soundwaters.org/sails-rentals/rentals/",
  "https://www.amipaddleboard.com/",
  "",
  // "https://sunsetwatersportskeywest.com/tours-activities/parasailing/",
  // "https://flysobe.com/",
  // "https://www.catalinatours.com/tour/parasail-ride/",
  // "https://sunshinedestin.com/sandestin-parasailing/",
  // "https://www.kittyhawkwatersports.com/blog/parasailing-faq-everyone-should-try-it-at-least-once-in-their-lifetime/",
  // "https://www.furycat.com/",
  // "https://englewoodparasailing.com/",
  // "https://kswatersports.com/parasailing/",
  // "https://searocket.com/",
  // "https://www.robbies.com/",
  // "https://bonitajetski.com/",
  // "https://islandheadhhi.com/",
  // "https://funstpete.com/",
  // "https://parasailorangebeach.com/",
  // "https://siestakeywatersports.com/",
  // "https://ufoparasail.net/",
  // "https://veniceparasailingandtours.com/"
]